// daily-reports.jsx — Daily Reports host page.
// Top: today's report — a "document cover" panel where the auto-generated
// doc will be embedded. Below: 7-day archive strip.

const TODAY = {
  weekday: 'Friday',
  day: '15',
  month: 'May',
  year: '2026',
  cycle: '142',
  publishedAt: '07:00 UTC',
  generatedAt: '06:58 UTC',
  // Document metadata
  pages: '12',
  readTime: '≈6 min read',
  format: 'PDF',
  modelVersion: '0.4.2',
  // Table of contents — the structure of every daily report
  toc: [
    'Market overview',
    'BTC analysis',
    'ETH analysis',
    'Sentiment summary',
    'Risk flags',
    'Today’s signals',
    'Tomorrow’s watchlist',
    'Methodology notes',
  ],
};

// Past 7 days (today is Friday May 15, 2026; archive = preceding 7 days)
const ARCHIVE = [
  { dow: 'Thu', day: '14', month: 'May', cycle: '141', status: 'Published' },
  { dow: 'Wed', day: '13', month: 'May', cycle: '140', status: 'Published' },
  { dow: 'Tue', day: '12', month: 'May', cycle: '139', status: 'Published' },
  { dow: 'Mon', day: '11', month: 'May', cycle: '138', status: 'Published' },
  { dow: 'Sun', day: '10', month: 'May', cycle: '137', status: 'Published' },
  { dow: 'Sat', day: '09', month: 'May', cycle: '136', status: 'Published' },
  { dow: 'Fri', day: '08', month: 'May', cycle: '135', status: 'Published' },
];

// ─── page hero ────────────────────────────────────────────────────────────────
function DailyPageHero({ t }) {
  return (
    <section style={{ padding: '92px 56px 50px', position: 'relative', overflow: 'hidden' }}>
      <div style={{
        position: 'absolute', inset: 0,
        background: `radial-gradient(ellipse 60% 50% at 75% 35%, ${t.accentSoft} 0%, transparent 65%)`,
        pointerEvents: 'none',
      }} />
      <div style={{
        display: 'flex', alignItems: 'center', gap: 12,
        fontFamily: 'var(--ca-mono)', fontSize: 11, letterSpacing: '0.18em',
        color: t.fgMuted, textTransform: 'uppercase', marginBottom: 28,
        position: 'relative',
      }}>
        <span style={{ width: 22, height: 1, background: t.fgMuted }} />
        Daily reports
      </div>
      <div style={{ display: 'flex', gap: 60, alignItems: 'flex-end', position: 'relative' }}>
        <h1 style={{
          margin: 0, flex: 1, fontFamily: 'var(--ca-display)',
          fontWeight: 500, fontSize: 88, lineHeight: 1.0,
          letterSpacing: '-0.035em', color: t.fg, textWrap: 'balance',
          maxWidth: 980,
        }}>Today’s brief, every morning at 07:00 UTC.</h1>
        <div style={{ flex: '0 0 380px', paddingBottom: 14 }}>
          <p style={{
            margin: 0, fontFamily: 'var(--ca-display)', fontSize: 16,
            lineHeight: 1.6, color: t.fgSoft,
          }}>A structured report is generated by the model at the end of each cycle and published here. Past reports remain available in the archive below.</p>
        </div>
      </div>

      {/* status band */}
      <div style={{
        marginTop: 56, display: 'flex', borderTop: `1px solid ${t.line}`,
        borderBottom: `1px solid ${t.line}`,
      }}>
        {[
          ['Latest', `Cycle ${TODAY.cycle}`],
          ['Published', `${TODAY.publishedAt}`],
          ['Coverage', 'BTC + ETH'],
          ['Author', `Model · v${TODAY.modelVersion}`],
          ['Archive', '7 days'],
        ].map(([k, v], i, arr) => (
          <div key={k} style={{
            flex: 1, padding: '22px 26px',
            borderRight: i < arr.length - 1 ? `1px solid ${t.line}` : 'none',
            display: 'flex', flexDirection: 'column', gap: 6,
          }}>
            <span style={{ fontFamily: 'var(--ca-mono)', fontSize: 10, letterSpacing: '0.16em', color: t.fgMuted, textTransform: 'uppercase' }}>{k}</span>
            <span style={{ fontFamily: 'var(--ca-display)', fontSize: 17, color: t.fg, letterSpacing: '-0.01em' }}>{v}</span>
          </div>
        ))}
      </div>
    </section>
  );
}

// ─── today’s report card ──────────────────────────────────────────────────────────
function TodaysReport({ t }) {
  return (
    <section style={{ padding: '60px 56px 0' }}>
      <div style={{
        display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end',
        marginBottom: 30,
      }}>
        <div style={{
          display: 'flex', alignItems: 'center', gap: 12,
          fontFamily: 'var(--ca-mono)', fontSize: 11, letterSpacing: '0.18em',
          color: t.fgMuted, textTransform: 'uppercase',
        }}>
          <span style={{ width: 22, height: 1, background: t.fgMuted }} />
          Today’s brief
        </div>
        <div style={{
          display: 'inline-flex', alignItems: 'center', gap: 10,
          padding: '8px 14px', borderRadius: 999,
          border: `1px solid ${t.accent}`, background: t.accentSoft,
          fontFamily: 'var(--ca-mono)', fontSize: 11, letterSpacing: '0.14em',
          color: t.accent, textTransform: 'uppercase',
        }}>
          <span style={{ width: 7, height: 7, borderRadius: 999, background: t.accent, boxShadow: `0 0 8px ${t.accent}` }} />
          Published
        </div>
      </div>

      <div style={{
        position: 'relative', overflow: 'hidden',
        border: `1px solid ${t.line}`, borderRadius: 22,
        background: t.bgPanel,
      }}>
        <div style={{
          position: 'absolute', top: 0, right: 0, width: 360, height: 360,
          background: `radial-gradient(circle at 100% 0%, ${t.accentSoft} 0%, transparent 70%)`,
          pointerEvents: 'none',
        }} />

        <div style={{ display: 'flex', position: 'relative' }}>
          {/* ── LEFT: report "cover" / content preview ───────────────── */}
          <div style={{
            flex: '1.45 1 0', padding: '52px 56px 56px',
            borderRight: `1px solid ${t.line}`,
          }}>
            {/* date strip */}
            <div style={{
              display: 'flex', alignItems: 'center', gap: 18,
              fontFamily: 'var(--ca-mono)', fontSize: 11, letterSpacing: '0.16em',
              color: t.fgMuted, textTransform: 'uppercase', marginBottom: 32,
            }}>
              <span style={{ color: t.fg }}>{TODAY.weekday}</span>
              <span style={{ width: 4, height: 4, borderRadius: 999, background: t.fgDim }} />
              <span>{TODAY.day} {TODAY.month} {TODAY.year}</span>
              <span style={{ width: 4, height: 4, borderRadius: 999, background: t.fgDim }} />
              <span>Cycle {TODAY.cycle}</span>
            </div>

            {/* big title */}
            <h2 style={{
              margin: 0, fontFamily: 'var(--ca-display)', fontWeight: 500,
              fontSize: 64, lineHeight: 1.02, letterSpacing: '-0.035em',
              color: t.fg, textWrap: 'balance', maxWidth: 720,
            }}>Daily Brief</h2>
            <div style={{
              marginTop: 14, fontFamily: 'var(--ca-display)', fontSize: 24,
              color: t.fgSoft, letterSpacing: '-0.015em', lineHeight: 1.25,
            }}>BTC + ETH · Model overview for the European session.</div>

            <div style={{
              marginTop: 44,
              padding: '24px 26px',
              border: `1px dashed ${t.line}`, borderRadius: 14,
              background: t.bg,
              fontFamily: 'var(--ca-display)', fontSize: 14,
              color: t.fgMuted, lineHeight: 1.6,
              display: 'flex', alignItems: 'flex-start', gap: 14,
            }}>
              <span style={{
                flex: '0 0 auto', marginTop: 4, width: 8, height: 8,
                borderRadius: 999, background: t.accent,
                boxShadow: `0 0 8px ${t.accent}`,
              }} />
              <span>
                <span style={{
                  fontFamily: 'var(--ca-mono)', fontSize: 10, letterSpacing: '0.14em',
                  color: t.accent, textTransform: 'uppercase',
                  display: 'block', marginBottom: 6,
                }}>Report body</span>
                The day’s narrative — sentiment, market structure, signals — is delivered inside the report document. Open the report in the browser, or download the PDF, using the actions on the right.
              </span>
            </div>

            {/* table of contents */}
            <div style={{ marginTop: 44 }}>
              <div style={{
                fontFamily: 'var(--ca-mono)', fontSize: 10, letterSpacing: '0.18em',
                color: t.fgMuted, textTransform: 'uppercase', marginBottom: 22,
              }}>In this brief</div>
              <div style={{
                display: 'grid', gridTemplateColumns: '1fr 1fr', columnGap: 48,
              }}>
                {[TODAY.toc.slice(0, 4), TODAY.toc.slice(4)].map((col, ci) => (
                  <ol key={ci} start={ci * 4 + 1} style={{
                    margin: 0, padding: 0, listStyle: 'none',
                  }}>
                    {col.map((item, i) => (
                      <li key={i} style={{
                        display: 'flex', gap: 18, alignItems: 'baseline',
                        padding: '14px 0',
                        borderBottom: `1px solid ${t.lineSoft}`,
                      }}>
                        <span style={{
                          fontFamily: 'var(--ca-mono)', fontSize: 11, color: t.fgMuted,
                          flex: '0 0 24px', letterSpacing: '0.05em',
                        }}>{String(ci * 4 + i + 1).padStart(2, '0')}</span>
                        <span style={{
                          fontFamily: 'var(--ca-display)', fontSize: 16,
                          color: t.fg, letterSpacing: '-0.005em', lineHeight: 1.4,
                        }}>{item}</span>
                      </li>
                    ))}
                  </ol>
                ))}
              </div>
            </div>
          </div>

          {/* ── RIGHT: document metadata + actions ───────────────────── */}
          <div style={{
            flex: '1 1 0', padding: '52px 48px 56px',
            display: 'flex', flexDirection: 'column',
            background: t.bg,
          }}>
            <div style={{
              fontFamily: 'var(--ca-mono)', fontSize: 10, letterSpacing: '0.18em',
              color: t.fgMuted, textTransform: 'uppercase', marginBottom: 26,
            }}>Document</div>

            {/* doc preview thumbnail */}
            <div style={{
              border: `1px solid ${t.line}`, borderRadius: 14,
              background: t.bgPanel,
              padding: '28px 28px',
              marginBottom: 30, position: 'relative', minHeight: 220,
              display: 'flex', flexDirection: 'column', justifyContent: 'space-between',
              overflow: 'hidden',
            }}>
              <div style={{
                position: 'absolute', top: 14, right: 14,
                padding: '4px 8px', borderRadius: 4,
                fontFamily: 'var(--ca-mono)', fontSize: 9, letterSpacing: '0.16em',
                color: t.accent, textTransform: 'uppercase',
                border: `1px solid ${t.accent}`,
              }}>PDF</div>
              <div>
                <div style={{
                  width: 36, height: 44, borderRadius: 4,
                  background: t.bg, border: `1px solid ${t.line}`,
                  position: 'relative',
                }}>
                  <div style={{ position: 'absolute', top: 8, left: 6, right: 6, height: 2, background: t.fgDim, borderRadius: 1 }} />
                  <div style={{ position: 'absolute', top: 14, left: 6, right: 10, height: 2, background: t.fgDim, borderRadius: 1, opacity: 0.7 }} />
                  <div style={{ position: 'absolute', top: 20, left: 6, right: 8, height: 2, background: t.fgDim, borderRadius: 1, opacity: 0.5 }} />
                  <div style={{ position: 'absolute', top: 26, left: 6, right: 12, height: 2, background: t.fgDim, borderRadius: 1, opacity: 0.4 }} />
                  <div style={{ position: 'absolute', top: 32, left: 6, right: 9, height: 2, background: t.fgDim, borderRadius: 1, opacity: 0.3 }} />
                </div>
              </div>
              <div style={{ marginTop: 18 }}>
                <div style={{
                  fontFamily: 'var(--ca-mono)', fontSize: 10, letterSpacing: '0.14em',
                  color: t.fgMuted, textTransform: 'uppercase', marginBottom: 6,
                }}>Filename</div>
                <div style={{
                  fontFamily: 'var(--ca-mono)', fontSize: 13, color: t.fg,
                  letterSpacing: '-0.005em', wordBreak: 'break-all',
                }}>daily-brief_2026-05-15_c142.pdf</div>
              </div>
            </div>

            {/* meta rows */}
            <div style={{
              borderTop: `1px solid ${t.line}`,
            }}>
              {[
                ['Sections', TODAY.toc.length.toString()],
                ['Read time', TODAY.readTime],
                ['Pages', TODAY.pages],
                ['Format', TODAY.format],
                ['Generated', TODAY.generatedAt],
                ['Author', `Model · v${TODAY.modelVersion}`],
              ].map(([k, v]) => (
                <div key={k} style={{
                  display: 'flex', justifyContent: 'space-between',
                  padding: '14px 0', borderBottom: `1px solid ${t.lineSoft}`,
                }}>
                  <span style={{
                    fontFamily: 'var(--ca-mono)', fontSize: 11, letterSpacing: '0.06em',
                    color: t.fgMuted, textTransform: 'uppercase',
                  }}>{k}</span>
                  <span style={{
                    fontFamily: 'var(--ca-display)', fontSize: 14, color: t.fg,
                    letterSpacing: '-0.005em',
                  }}>{v}</span>
                </div>
              ))}
            </div>

            <div style={{ flex: 1 }} />

            {/* CTAs */}
            <div style={{ marginTop: 32, display: 'flex', flexDirection: 'column', gap: 10 }}>
              <button style={{
                background: t.accent, color: t.accentInk, border: 'none',
                padding: '15px 22px', borderRadius: 12,
                fontFamily: 'var(--ca-display)', fontSize: 15, fontWeight: 500,
                letterSpacing: '-0.005em', cursor: 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              }}>
                <span>Read in browser</span>
                <span style={{ fontSize: 17, lineHeight: 1 }}>↗</span>
              </button>
              <button style={{
                background: 'transparent', color: t.fg, border: `1px solid ${t.line}`,
                padding: '15px 22px', borderRadius: 12,
                fontFamily: 'var(--ca-display)', fontSize: 15, fontWeight: 500,
                letterSpacing: '-0.005em', cursor: 'pointer',
                display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              }}>
                <span>Download PDF</span>
                <span style={{ fontSize: 17, lineHeight: 1 }}>↓</span>
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

// ─── archive ───────────────────────────────────────────────────────────────────
function ArchiveCard({ t, r }) {
  return (
    <div className="reports-archivecard" style={{
      flex: 1, padding: '22px 22px 24px',
      border: `1px solid ${t.line}`, borderRadius: 14,
      background: t.bgPanel, position: 'relative', overflow: 'hidden',
      display: 'flex', flexDirection: 'column', minHeight: 230,
      transition: 'transform .25s cubic-bezier(.2,.8,.2,1), border-color .25s, background .25s',
      cursor: 'pointer',
    }}>
      <div style={{
        display: 'flex', alignItems: 'center', justifyContent: 'space-between',
        marginBottom: 22,
      }}>
        <span style={{
          fontFamily: 'var(--ca-mono)', fontSize: 11, letterSpacing: '0.14em',
          color: t.fgMuted, textTransform: 'uppercase',
        }}>{r.dow}</span>
        <span style={{ width: 6, height: 6, borderRadius: 999, background: t.accent, boxShadow: `0 0 6px ${t.accent}` }} />
      </div>
      <div style={{
        fontFamily: 'var(--ca-display)', fontWeight: 500, fontSize: 46,
        color: t.fg, letterSpacing: '-0.04em', lineHeight: 0.95,
      }}>{r.day}</div>
      <div style={{
        marginTop: 6, fontFamily: 'var(--ca-mono)', fontSize: 11,
        color: t.fgMuted, letterSpacing: '0.12em', textTransform: 'uppercase',
      }}>{r.month}</div>
      <div style={{ flex: 1 }} />
      <div style={{
        marginTop: 24, paddingTop: 14, borderTop: `1px dashed ${t.line}`,
      }}>
        <div style={{
          fontFamily: 'var(--ca-mono)', fontSize: 10, letterSpacing: '0.14em',
          color: t.fgMuted, textTransform: 'uppercase', marginBottom: 4,
        }}>Cycle {r.cycle}</div>
        <div style={{
          display: 'flex', justifyContent: 'space-between', alignItems: 'center',
          fontFamily: 'var(--ca-display)', fontSize: 13,
        }}>
          <span style={{ color: t.fgSoft }}>{r.status}</span>
          <span style={{ color: t.fg }}>View &rarr;</span>
        </div>
      </div>
    </div>
  );
}

function ArchiveSection({ t }) {
  return (
    <section style={{ padding: '120px 56px 100px' }}>
      <div style={{
        display: 'flex', justifyContent: 'space-between', alignItems: 'flex-end',
        marginBottom: 50,
      }}>
        <div>
          <div style={{
            display: 'flex', alignItems: 'center', gap: 12,
            fontFamily: 'var(--ca-mono)', fontSize: 11, letterSpacing: '0.18em',
            color: t.fgMuted, textTransform: 'uppercase', marginBottom: 24,
          }}>
            <span style={{ width: 22, height: 1, background: t.fgMuted }} />
            Archive
          </div>
          <h2 style={{
            margin: 0, fontFamily: 'var(--ca-display)', fontWeight: 500,
            fontSize: 56, lineHeight: 1.02, letterSpacing: '-0.035em', color: t.fg,
            textWrap: 'balance', maxWidth: 760,
          }}>Past seven days.</h2>
          <p style={{
            margin: '20px 0 0', maxWidth: 540,
            fontFamily: 'var(--ca-display)', fontSize: 15, lineHeight: 1.55,
            color: t.fgSoft,
          }}>Select a date to open that day’s brief. Reports older than seven days are kept in the cohort drive.</p>
        </div>
        <div style={{ display: 'flex', gap: 10, paddingBottom: 6 }}>
          <button style={{
            background: 'transparent', color: t.fg, border: `1px solid ${t.line}`,
            padding: '11px 16px', borderRadius: 10,
            fontFamily: 'var(--ca-display)', fontSize: 13, cursor: 'pointer',
            display: 'inline-flex', alignItems: 'center', gap: 8,
          }}>
            <span style={{ fontSize: 14, lineHeight: 1 }}>←</span>
            Previous week
          </button>
          <button style={{
            background: 'transparent', color: t.fg, border: `1px solid ${t.line}`,
            padding: '11px 16px', borderRadius: 10,
            fontFamily: 'var(--ca-display)', fontSize: 13, cursor: 'pointer',
            display: 'inline-flex', alignItems: 'center', gap: 8,
          }}>
            Open full archive
            <span style={{ fontSize: 14, lineHeight: 1 }}>↗</span>
          </button>
        </div>
      </div>
      <div style={{ display: 'flex', gap: 12 }}>
        {ARCHIVE.map((r) => <ArchiveCard key={r.cycle} t={t} r={r} />)}
      </div>
    </section>
  );
}

// ─── page ───────────────────────────────────────────────────────────────────
function DailyReports() {
  const t = THEMES.greenDark;
  return (
    <div style={{
      width: '100%', minHeight: '100%', background: t.bg, color: t.fg,
      fontFamily: 'var(--ca-display)', position: 'relative', overflow: 'hidden',
    }}>
      <Nav t={t} active="Daily Reports" />
      <DailyPageHero t={t} />
      <TodaysReport t={t} />
      <ArchiveSection t={t} />
      <Footer t={t} />
    </div>
  );
}

window.DailyReports = DailyReports;
